#-------------------------------
# General Site Settings
title: Changwoo Han
logo: logo.jpeg # You can add own logo.
description: Changwoo's personal blog


#-------------------------------
# Author Settings
author:
  name: Changwoo Han
  image: 01.jpg
  say-hello: Hello, I’m <strong>Changwoo Han</strong>
  bio: I am environmental epidemiologist who researches about health effects of <strong> natural and environmental disasters</strong>. I share my researches, thoughts and daily life with this blog. Loves <a href="#">music</a> & my wife Judy.


#-------------------------------
# Contact links
twitter: https://x.com/nejm_han # Add your Twitter handle
facebook: https://www.facebook.com/hanchangwooo/ # Add your Facebook handle
instagram: https://www.instagram.com/nejm_han/ # Add your Instagram handle



#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: nejm_han # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
